# ext4 Tests Module

add_executable(ext4_tests
        ${CMAKE_CURRENT_LIST_DIR}/../../filesystem/ext4/ext4.cpp
        ${CMAKE_CURRENT_LIST_DIR}/../../filesystem/ext4/ext4_vfs_adapter.cpp
        ${CMAKE_CURRENT_LIST_DIR}/../../filesystem/ext4/ext4_time.cpp
        ${CMAKE_CURRENT_LIST_DIR}/../../lib/time.cpp
        ext4_tests_main.cpp
)
target_link_libraries(ext4_tests PRIVATE kernel_stubs)
target_compile_options(ext4_tests PRIVATE
        -DUNIT_TEST
        -fno-rtti
        -g
)

set(EXT4_IMG    ${CMAKE_CURRENT_BINARY_DIR}/test_ext4.img)
set(EXT4_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/create_ext4_img.sh)

add_custom_command(
        OUTPUT  ${EXT4_IMG}
        COMMAND bash ${EXT4_SCRIPT} ${EXT4_IMG}
        DEPENDS ${EXT4_SCRIPT}
        COMMENT "Generating test_ext4.img for ext4 VFS adapter tests"
)

add_custom_target(generate_ext4_test_img ALL
        DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/test_ext4.img)

add_dependencies(ext4_tests generate_ext4_test_img)

function(add_ext4_test SUITE NAME)
    add_test(
            NAME ${SUITE}.${NAME}
            COMMAND ext4_tests ${SUITE} ${NAME}
            WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )
endfunction()

add_ext4_test(Ext4_Find RootFindExistingEntry)
add_ext4_test(Ext4_Find RootFindExistingDirectory)
add_ext4_test(Ext4_Find FindMissingEntryReturnsNull)
add_ext4_test(Ext4_Find FindOnNullParentReturnsNull)
add_ext4_test(Ext4_Find FindOnFileNodeReturnsNull)
add_ext4_test(Ext4_Find FindInSubdirectory)
add_ext4_test(Ext4_Find FindChildPathIsCorrect)
add_ext4_test(Ext4_Find FindChildPathInSubdir)
add_ext4_test(Ext4_Find FindDotEntryReturnsNode)

add_ext4_test(Ext4_Opendir RootOpendirReturnsHandle)
add_ext4_test(Ext4_Opendir OpendirOnNullNodeReturnsNull)
add_ext4_test(Ext4_Opendir OpendirOnFileReturnsNull)
add_ext4_test(Ext4_Opendir SubdirOpendirReturnsHandle)
add_ext4_test(Ext4_Opendir MultipleOpendirCallsIndependent)

add_ext4_test(Ext4_Readdir ReadsAtLeastOneName)
add_ext4_test(Ext4_Readdir ReturnsZeroAtEnd)
add_ext4_test(Ext4_Readdir FindsHelloTxt)
add_ext4_test(Ext4_Readdir FindsSubdir)
add_ext4_test(Ext4_Readdir FindsDotAndDotDot)
add_ext4_test(Ext4_Readdir EntryCountMatchesDirect)
add_ext4_test(Ext4_Readdir NamesAreNullTerminated)
add_ext4_test(Ext4_Readdir SubdirContainsNestedTxt)
add_ext4_test(Ext4_Readdir IndependentHandlesProduceSameEntries)

add_ext4_test(Ext4_Closedir ClosedirOnNullIsNoop)
add_ext4_test(Ext4_Closedir ClosedirFreesHandle)
add_ext4_test(Ext4_Closedir ClosedirAfterFullDrain)
add_ext4_test(Ext4_Closedir ClosedirOnSubdirHandle)

add_ext4_test(Ext4_FileIO ReadHelloTxt)
add_ext4_test(Ext4_FileIO ReadHelloTxtWithOffset)
add_ext4_test(Ext4_FileIO ReadHelloTxtLastByte)
add_ext4_test(Ext4_FileIO ReadBeyondEOFReturnsZeroOrClamped)
add_ext4_test(Ext4_FileIO ReadFarBeyondEOF)
add_ext4_test(Ext4_FileIO ReadPartialLargerThanFile)
add_ext4_test(Ext4_FileIO ReadEmptyFileReturnsZero)
add_ext4_test(Ext4_FileIO ReadDirectoryFails)
add_ext4_test(Ext4_FileIO ReadNullNodeFails)
add_ext4_test(Ext4_FileIO ReadBinaryBinFirstBlock)
add_ext4_test(Ext4_FileIO ReadBinaryBinSecondBlock)
add_ext4_test(Ext4_FileIO ReadBinaryBinFull)
add_ext4_test(Ext4_FileIO ReadBinaryBinCrossBoundary)
add_ext4_test(Ext4_FileIO ReadBigBinFull)
add_ext4_test(Ext4_FileIO ReadBigBinAtOffset)
add_ext4_test(Ext4_FileIO WriteAndReadBack)
add_ext4_test(Ext4_FileIO WriteAtOffset)
add_ext4_test(Ext4_FileIO WriteMultiBlock)
add_ext4_test(Ext4_FileIO WriteLargeFile)
add_ext4_test(Ext4_FileIO WriteAllByteValues)
add_ext4_test(Ext4_FileIO WriteOverwriteSameSize)
add_ext4_test(Ext4_FileIO WriteToExistingFile)
add_ext4_test(Ext4_FileIO WriteToDirectoryFails)
add_ext4_test(Ext4_FileIO WriteNullNodeFails)
add_ext4_test(Ext4_FileIO FsReadFileReturnsCorrectBytes)
add_ext4_test(Ext4_FileIO FsWriteFilePersistsAcrossRead)
add_ext4_test(Ext4_FileIO NodeSizeMatchesActualContent)
add_ext4_test(Ext4_FileIO NodeSizeIsZeroForEmptyFile)

add_ext4_test(Ext4_Create CreateFileInRoot)
add_ext4_test(Ext4_Create CreateFileAppearsInListing)
add_ext4_test(Ext4_Create CreateFileIsRegularNode)
add_ext4_test(Ext4_Create CreateFileInitialSizeZero)
add_ext4_test(Ext4_Create CreateFileInSubdir)
add_ext4_test(Ext4_Create CreateFileWriteAndRead)
add_ext4_test(Ext4_Create CreateMultipleFiles)
add_ext4_test(Ext4_Create CreateFileNullParent)
add_ext4_test(Ext4_Create CreateFileNullName)
add_ext4_test(Ext4_Create CreateFileOnFileNodeFails)

add_ext4_test(Ext4_Unlink UnlinkRemovesFile)
add_ext4_test(Ext4_Unlink UnlinkMakesFindReturnNull)
add_ext4_test(Ext4_Unlink UnlinkMissingFileReturnsError)
add_ext4_test(Ext4_Unlink UnlinkNullParent)
add_ext4_test(Ext4_Unlink UnlinkNullName)
add_ext4_test(Ext4_Unlink UnlinkExistingImageFile)
add_ext4_test(Ext4_Unlink UnlinkFromSubdir)
add_ext4_test(Ext4_Unlink CreateWriteUnlinkCycle)

add_ext4_test(Ext4_Mkdir MkdirInRoot)
add_ext4_test(Ext4_Mkdir MkdirAppearsInListing)
add_ext4_test(Ext4_Mkdir MkdirNodeIsDirectory)
add_ext4_test(Ext4_Mkdir MkdirHasDotEntries)
add_ext4_test(Ext4_Mkdir MkdirNullParent)
add_ext4_test(Ext4_Mkdir MkdirNullName)
add_ext4_test(Ext4_Mkdir MkdirOnFileNodeFails)
add_ext4_test(Ext4_Mkdir MkdirThenCreateFileInside)

add_ext4_test(Ext4_Rmdir RmdirEmptyDir)
add_ext4_test(Ext4_Rmdir RmdirMakesFindReturnNull)
add_ext4_test(Ext4_Rmdir RmdirNonEmptyFails)
add_ext4_test(Ext4_Rmdir RmdirExistingImageDir)
add_ext4_test(Ext4_Rmdir RmdirMissingReturnsError)
add_ext4_test(Ext4_Rmdir RmdirNullParent)
add_ext4_test(Ext4_Rmdir RmdirNullName)
add_ext4_test(Ext4_Rmdir MkdirRmdirCycleIsRepeatable)

add_ext4_test(Ext4_Rename RenameBasic)
add_ext4_test(Ext4_Rename RenamePreservesContent)
add_ext4_test(Ext4_Rename RenameImageFile)
add_ext4_test(Ext4_Rename RenamePreservesImageFileContent)
add_ext4_test(Ext4_Rename RenameDirectory)
add_ext4_test(Ext4_Rename RenameDirectoryContentPreserved)
add_ext4_test(Ext4_Rename RenameCrossDirectory)
add_ext4_test(Ext4_Rename RenameCrossDirectoryPreservesContent)
add_ext4_test(Ext4_Rename RenameMissingSourceReturnsError)
add_ext4_test(Ext4_Rename RenameNullOldParent)
add_ext4_test(Ext4_Rename RenameNullOldName)
add_ext4_test(Ext4_Rename RenameNullNewParent)
add_ext4_test(Ext4_Rename RenameNullNewName)
add_ext4_test(Ext4_Rename RenameFromFileNodeFails)
add_ext4_test(Ext4_Rename FsRenameRoundTrip)

add_ext4_test(Ext4_Stat StatRootDirSucceeds)
add_ext4_test(Ext4_Stat StatRegularFileSucceeds)
add_ext4_test(Ext4_Stat StatDirectorySucceeds)
add_ext4_test(Ext4_Stat StatNullNodeFails)
add_ext4_test(Ext4_Stat StatNullOutFails)
add_ext4_test(Ext4_Stat StatHelloTxtSize)
add_ext4_test(Ext4_Stat StatEmptyFileSize)
add_ext4_test(Ext4_Stat StatBinaryBinSize)
add_ext4_test(Ext4_Stat StatBigBinSize)
add_ext4_test(Ext4_Stat StatRootDirModeIsDirectory)
add_ext4_test(Ext4_Stat StatSubdirModeIsDirectory)
add_ext4_test(Ext4_Stat StatRegularFileModeIsFile)
add_ext4_test(Ext4_Stat StatBinaryFileModeIsFile)
add_ext4_test(Ext4_Stat StatRootInodeIsTwo)
add_ext4_test(Ext4_Stat StatInodeDiffersAcrossFiles)
add_ext4_test(Ext4_Stat StatFileDiffersFromDirectory)
add_ext4_test(Ext4_Stat StatSizeMatchesNodeSize)
add_ext4_test(Ext4_Stat StatSizeMatchesNodeSizeBigFile)
add_ext4_test(Ext4_Stat StatAfterCreateReflectsNewFile)
add_ext4_test(Ext4_Stat FsStatRootInode)

add_ext4_test(Ext4_Truncate ShrinkReducesReadableBytes)
add_ext4_test(Ext4_Truncate ShrinkUpdatesNodeSize)
add_ext4_test(Ext4_Truncate ShrinkPreservesLeadingBytes)
add_ext4_test(Ext4_Truncate ShrinkBinaryFile)
add_ext4_test(Ext4_Truncate ShrinkToOneByte)
add_ext4_test(Ext4_Truncate TruncateToZeroMakesFileSizeZero)
add_ext4_test(Ext4_Truncate TruncateToZeroMakesReadReturnZero)
add_ext4_test(Ext4_Truncate TruncateToZeroThenWrite)
add_ext4_test(Ext4_Truncate TruncateToZeroOnLargeFile)
add_ext4_test(Ext4_Truncate TruncateToSameSizeIsNoOp)
add_ext4_test(Ext4_Truncate ExtendIncreasesSize)
add_ext4_test(Ext4_Truncate ExtendPreservesOriginalContent)
add_ext4_test(Ext4_Truncate TruncateNullNodeFails)
add_ext4_test(Ext4_Truncate TruncateDirectoryFails)
add_ext4_test(Ext4_Truncate FsTruncateShrinksFile)

add_ext4_test(Ext4_FS ValidImageIsValid)
add_ext4_test(Ext4_FS InvalidAllZeroImageIsNotValid)
add_ext4_test(Ext4_FS InvalidAllFFImageIsNotValid)
add_ext4_test(Ext4_FS InvalidSmallDeviceIsNotValid)
add_ext4_test(Ext4_FS SuperblockMagicIsCorrect)
add_ext4_test(Ext4_FS SuperblockLabelIsVespTest)
add_ext4_test(Ext4_FS SuperblockInodeCountIsPositive)
add_ext4_test(Ext4_FS SuperblockBlockCountIsPositive)
add_ext4_test(Ext4_FS BlockSizeIs4096)
add_ext4_test(Ext4_FS BlockSizeIsPowerOfTwo)
add_ext4_test(Ext4_FS ProbeDetectsExt4)
add_ext4_test(Ext4_FS ProbeExtractsLabel)
add_ext4_test(Ext4_FS ProbeRejectsZeroedDevice)
add_ext4_test(Ext4_FS RootInodeIsTwo)
add_ext4_test(Ext4_FS RootNodeIsDirectory)
add_ext4_test(Ext4_FS RootNodeIsPermanent)
add_ext4_test(Ext4_FS ReadDirectoryRootHasExpectedEntries)
add_ext4_test(Ext4_FS ReadDirectoryListMatchesFindPath)
add_ext4_test(Ext4_FS FindDeepDirectoryLevel1)
add_ext4_test(Ext4_FS FindDeepDirectoryLevel2)
add_ext4_test(Ext4_FS FindDeepLeafFile)
add_ext4_test(Ext4_FS StressCreateWriteReadDelete10Files)
add_ext4_test(Ext4_FS StressCreateManyFilesInSubdir)
add_ext4_test(Ext4_FS StressMixedOperations)
add_ext4_test(Ext4_FS StressMultiBlockWriteReadCycles)