// ext4_fixture.h
// VesperaOS - operating system for the x86_64 architecture
//
// Copyright (c) 2026 Linus Genz <linuslinuxgenz@gmail.com>
//
// Created by Linus Genz on 25.03.26.
//
// This file is part of VesperaOS.
//
// VesperaOS is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// VesperaOS is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with VesperaOS. If not, see <https://www.gnu.org/licenses/>.

#ifndef VESPERAOS_EXT4_FIXTURE_H
#define VESPERAOS_EXT4_FIXTURE_H

#include "../../filesystem/vfs/fs_registry.h"
#include "../../filesystem/ext4/ext4.h"
#include "../../filesystem/ext4/ext4_vfs_adapter.h"
#include "../framework/test_framework.h"
#include "../stub_kernel/mock_blockdevice.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Ext4Fixture
//
// Loads a pre-formatted ext4 image from "test_ext4.img" (generated by the
// CMakeLists.txt custom command) and exposes the ext4::FileSystem together
// with thin wrappers for the four VFS adapter functions under test:
//   ext4_find, ext4_opendir, ext4_readdir, ext4_closedir.
//
// The adapter functions are file-scoped statics in ext4_vfs_adapter.cpp, so
// we call them indirectly through a VfsNode whose ops pointer is set up by
// ext4_mount().  The fixture keeps the root VfsNode alive for the lifetime of
// each test.
// ---------------------------------------------------------------------------

// Forward-declare the driver symbol exposed by ext4_vfs_adapter.cpp.
extern FileSystemDriver ext4_driver;

struct Ext4Fixture {
    BlockDevice*      dev  = nullptr;
    ext4::FileSystem* fs   = nullptr;
    VfsNode*          root = nullptr;

    Ext4Fixture() {
        FILE* f = fopen("test_ext4.img", "rb");
        if (!f) {
            fprintf(stderr, "ERROR: test_ext4.img not found\n");
            return;
        }

        fseek(f, 0, SEEK_END);
        size_t size = static_cast<size_t>(ftell(f));
        rewind(f);

        // We need at least 1 MiB for a minimal ext4.
        constexpr size_t MIN_SIZE = 1u * 1024 * 1024;
        if (size < MIN_SIZE) {
            fprintf(stderr, "ERROR: test_ext4.img too small (%zu bytes)\n", size);
            fclose(f);
            return;
        }

        size_t sectors = size / MockBlockDevice::SECTOR_SIZE;
        auto*  mdev    = new MockBlockDevice(sectors);
        fread(mdev->raw(), 1, size, f);
        fclose(f);

        dev = mdev;

        // Use the driver's mount() to obtain the root VfsNode — this also
        // allocates and initialises the FileSystem object internally.
        root = ext4_driver.mount(dev);
        if (!root) {
            delete dev;
            dev = nullptr;
            return;
        }

        // Retrieve the FileSystem pointer from the root node's internal data
        // so individual tests can call fs->read_directory() directly.
        auto* nd = static_cast<Ext4Node*>(root->internal_data);
        fs = nd->fs;
    }

    ~Ext4Fixture() {
        if (root) {
            ext4_driver.unmount(root);
            // unmount currently does not free the node; free it manually.
            auto* nd = static_cast<Ext4Node*>(root->internal_data);
            if (nd) kernel::memory::free(nd);
            kernel::memory::free(root);
        }
        // dev is owned by the FileSystem after mount; don't double-free.
        // (In the real kernel the driver owns dev — here we just let it leak
        //  since MockBlockDevice has no kernel destructor path.)
    }

    [[nodiscard]] bool valid() const {
        return root != nullptr && fs != nullptr && fs->is_valid();
    }

    // -----------------------------------------------------------------------
    // find(parent, name) — delegates to root->ops->find
    // -----------------------------------------------------------------------
    VfsNode* find(VfsNode* parent, const char* name) const {
        if (!parent || !parent->ops || !parent->ops->find) return nullptr;
        return parent->ops->find(parent, name);
    }

    // -----------------------------------------------------------------------
    // list(node) — opens the directory, collects names, closes it
    // -----------------------------------------------------------------------
    std::vector<std::string> list(VfsNode* node) const {
        std::vector<std::string> names;
        if (!node || !node->ops) return names;

        void* handle = node->ops->opendir(node);
        if (!handle) return names;

        dirent_t de{};
        while (node->ops->readdir(handle, &de) == 1)
            names.emplace_back(de.name);

        node->ops->closedir(handle);
        return names;
    }

    // -----------------------------------------------------------------------
    // list_root() — convenience wrapper
    // -----------------------------------------------------------------------
    std::vector<std::string> list_root() const {
        return list(root);
    }

    static bool list_contains(const std::vector<std::string>& lst, const char* name) {
        for (auto& s : lst)
            if (s == name) return true;
        return false;
    }
};

#define WITH_EXT4(var)                                                                               \
    Ext4Fixture var;                                                                                  \
    if (!(var).valid()) {                                                                             \
        TestFramework::fail_test(__FILE__, __LINE__,                                                  \
            "Ext4Fixture invalid — is test_ext4.img present and valid?");                             \
        return;                                                                                       \
    }

#endif // VESPERAOS_EXT4_FIXTURE_H