#ifndef XHCI_TRB_H
#define XHCI_TRB_H

#include "xhci_common.h"
#include <vespera/types.h>

/*
// xHci Spec Section 4.11 Figure 4-13: TRB Template (page 188)

This section discusses the properties and uses of TRBs that are outside of the
scope of the general data structure descriptions that are provided in section
6.4.
*/
typedef struct XHCI_TRANSFER_REQUEST_BLOCK {
    u64 parameter; // TRB-specific parameter
    u32 status;    // Status information
    union {
        struct {
            u32 cycle_bit               : 1;
            u32 eval_next_trb           : 1;
            u32 interrupt_on_short_pkt  : 1;
            u32 no_snoop                : 1;
            u32 chain_bit               : 1;
            u32 interrupt_on_completion : 1;
            u32 immediate_data          : 1;
            u32 rsvd0                   : 2;
            u32 block_event_interrupt   : 1;
            u32 trb_type                : 6;
            u32 rsvd1                   : 16;
        };
        u32 control; // Control bits, including the TRB type
    };
} xhci_trb_t;
static_assert(sizeof(xhci_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_COMMAND_COMPLETION_REQUEST_BLOCK {
    u64 command_trb_pointer;
    struct {
        u32 rsvd0           : 24;
        u32 completion_code : 8;
    };
    struct {
        u32 cycle_bit   : 1;
        u32 rsvd1       : 9;
        u32 trb_type    : 6;
        u32 vfid        : 8;
        u32 slot_id     : 8;
    };
} xhci_command_completion_trb_t;
static_assert(sizeof(xhci_command_completion_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_ADDRESS_DEVICE_REQUEST_BLOCK {
    u64 input_context_physical_base;
    u32 rsvd;
    struct {
        u32 cycle_bit   : 1;
        u32 rsvd1       : 8;

        u32 bsr        : 1; // Block Set Address Request bit

        u32 trb_type   : 6;
        u32 rsvd2      : 8;
        u32 slot_id    : 8;
    };
} xhci_address_device_command_trb_t;
static_assert(sizeof(xhci_address_device_command_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_PORT_STATUS_CHANGE_REQUEST_BLOCK {
    struct {
        u32 rsvd0   : 24;
        u32 port_id : 8;
    };
    u32 rsvd1;
    struct {
        u32 rsvd2           : 24;
        u32 completion_code : 8;
    };
    struct {
        u32 cycle_bit  : 1;
        u32 rsvd3      : 9;
        u32 trb_type   : 6;
        u32 rsvd4      : 16;
    };
} xhci_port_status_change_trb_t;
static_assert(sizeof(xhci_port_status_change_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 4.11.2.2 Figure 4-14 SETUP Data, the Parameter Component of Setup Stage TRB (page 211)
*/
struct XHCI_DEVICE_REQUEST_PACKET {
    union {
        struct {
            /*
                0       = Device
                1       = Interface
                2       = Endpoint
                3       = Other
                4..31   = Reserved
            */
            u8 recipient           : 5;
            /*
                0       = Standard
                1       = Class
                2       = Vendor
                3       = Reserved
            */
            u8 type                : 2;
            /*
                0       = Host to Device
                1       = Device to Host
            */
            u8 transfer_direction   : 1;
        };
        u8 b_request_type;
    };

    u8 b_request;
    u16 w_value;
    u16 w_index;
    u16 w_length;
};
static_assert(sizeof(XHCI_DEVICE_REQUEST_PACKET) == 8);

/*
// xHci Spec Section 6.4.1.2.1 Setup Stage TRB (page 468)

A Setup Stage TRB is created by system software to initiate a USB Setup packet
on a control endpoint. Refer to section 3.2.9 for more information on Setup
Stage TRBs and the operation of control endpoints. Also refer to section 8.5.3 in
the USB2 spec. for a description of “Control Transfers”.
*/
typedef struct XHCI_SETUP_STAGE_TRANSFER_REQUEST_BLOCK {
    XHCI_DEVICE_REQUEST_PACKET request_packet;

    struct {
        // Always 8
        u32 trb_transfer_length  : 17;

        // Reserved
        u32 rsvd0                : 5;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target   : 10;
    };

    struct {
        u32 cycle_bit       : 1;
        u32 rsvd1           : 4;
        u32 ioc             : 1;
        u32 idt             : 1;
        u32 rsvd2           : 3;
        u32 trb_type        : 6;
        /*
            0 No Data Stage
            1 Reserved
            2 OUT Data Stage
            3 IN Data Stage
            Refer to section 4.11.2.2 for more information on the use of TRT.
        */
        u32 trt            : 2;
        u32 rsvd3          : 14;
    };
} xhci_setup_stage_trb_t;
static_assert(sizeof(xhci_setup_stage_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 6.4.1.2.2 Data Stage TRB Figure 6-10: Data Stage TRB (page 470)

A Data Stage TRB is used generate the Data stage transaction of a USB Control
transfer. Refer to section 3.2.9 for more information on Control transfers and
the operation of control endpoints. Also refer to section 8.5.3 in the USB2 spec.
for a description of “Control Transfers”.
*/
typedef struct XHCI_DATA_STAGE_TRANSFER_REQUEST_BLOCK {
    /*
        Data Buffer Pointer Hi and Lo. These fields represent the 64-bit address of the Data
        buffer area for this transaction.

        The memory structure referenced by this physical memory pointer is allowed to begin on
        a byte address boundary. However, user may find other alignments, such as 64-byte or
        128-byte alignments, to be more efficient and provide better performance.
    */
    u64 data_buffer;

    struct {
        /*
            TRB Transfer Length. For an OUT, this field is the number of data bytes the xHC will send
            during the execution of this TRB.

            For an IN, the initial value of the field identifies the size of the data buffer referenced
            by the Data Buffer Pointer, i.e. the number of bytes the host expects the endpoint to deliver.
            Valid values are 1 to 64K.
        */
        u32 trb_transfer_length  : 17;

        /*
            TD Size. This field provides an indicator of the number of packets remaining in the TD.
            Refer to section 4.11.2.4 for how this value is calculated.
        */
        u32 td_size             : 5;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target  : 10;
    };

    struct {
        u32 cycle_bit       : 1;
        u32 ent            : 1;
        u32 isp            : 1;
        u32 no_snoop        : 1;
        u32 chain          : 1;
        u32 ioc             : 1;
        u32 idt            : 1;
        u32 rsvd0          : 3;
        u32 trb_type        : 6;
        u32 dir            : 1;
        u32 rsvd1          : 15;
    };
} xhci_data_stage_trb_t;
static_assert(sizeof(xhci_data_stage_trb_t) == sizeof(u32) * 4);


/*
Refer to section 4.11.5.2 for more information
*/
typedef struct XHCI_EVENT_DATA_TRANSFER_REQUEST_BLOCK {
    u64 data;

    struct {
        u32 rsvd0              : 22;
        u32 interrupter_target  : 10;
    };

    struct {
        u32 cycle_bit       : 1;
        u32 ent            : 1;
        u32 rsvd1          : 2;
        u32 chain          : 1;
        u32 ioc            : 1;
        u32 rsvd2          : 3;
        u32 bei            : 1;
        u32 trb_type        : 6;
        u32 rsvd3          : 16;
    };
} xhci_event_data_trb_t;
static_assert(sizeof(xhci_event_data_trb_t) == sizeof(u32) * 4);

/*
// xHci Spec Section 6.4.1.2.3 Status Stage TRB Figure 6-11: Status Stage TRB (page 472).

A Status Stage TRB is used to generate the Status stage transaction of a USB
Control transfer. Refer to section 3.2.9 for more information on Control transfers
and the operation of control endpoints.
*/
typedef struct XHCI_STATUS_STAGE_TRANSFER_REQUEST_BLOCK {
    // Reserved
    u64 rsvd0;

    struct {
        // Reserved
        u32 rsvd1              : 22;

        /*
            This field defines the index of the Interrupter that will receive events
            generated by this TRB. Valid values are between 0 and MaxIntrs-1.
        */
        u32 interrupter_target  : 10;
    };

    struct {
        u32 cycle_bit       : 1;
        u32 ent            : 1;
        u32 rsvd2          : 2;
        u32 chain          : 1;
        u32 ioc            : 1;
        u32 rsvd3          : 4;
        u32 trb_type        : 6;
        u32 dir            : 1;
        u32 rsvd4          : 15;
    };
} xhci_status_stage_trb_t;
static_assert(sizeof(xhci_status_stage_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_TRANSFER_COMPLETION_REQUEST_BLOCK {
    u64 transfer_trb_pointer;
    struct {
        u32 transfer_length : 24;
        u32 completion_code : 8;
    };
    struct {
        u32 cycle_bit   : 1;
        u32 rsvd1       : 1;
        u32 event_data  : 1;
        u32 rsvd2       : 7;
        u32 trb_type    : 6;
        u32 endpoint_id : 5;
        u32 rsvd3       : 3;
        u32 slot_id     : 8;
    };
} xhci_transfer_completion_trb_t;
static_assert(sizeof(xhci_transfer_completion_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_EVALUATE_CONTEXT_COMMAND_REQUEST_BLOCK {
    u64 input_context_physical_base;
    u32 rsvd0;
    struct {
        u32 cycle_bit  : 1;
        u32 rsvd1      : 8;
        u32 rsvd2      : 1;
        u32 trb_type   : 6;
        u32 rsvd3      : 8;
        u32 slot_id    : 8;
    };
} xhci_evaluate_context_command_trb_t;
static_assert(sizeof(xhci_evaluate_context_command_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_CONFIGURE_ENDPOINT_COMMAND_REQUEST_BLOCK {
    u64 input_context_physical_base;
    u32 rsvd0;
    struct {
        u32 cycle_bit    : 1;
        u32 rsvd1        : 8;
        u32 deconfigure  : 1;
        u32 trb_type     : 6;
        u32 rsvd3        : 8;
        u32 slot_id      : 8;
    };
} xhci_configure_endpoint_command_trb_t;
static_assert(sizeof(xhci_configure_endpoint_command_trb_t) == sizeof(u32) * 4);

typedef struct XHCI_NORMAL_REQUEST_BLOCK {
    u64 data_buffer_physical_base;
    union {
        struct {
            u32 trb_transfer_length  : 17;
            u32 td_size             : 5;
            u32 interrupter_target  : 10;
        };
        u32 dword1;
    };
    struct {
        u32 cycle_bit       : 1;
        u32 ent            : 1;
        u32 isp            : 1;
        u32 no_snoop        : 1;
        u32 chain          : 1;
        u32 ioc             : 1;
        u32 idt            : 1;
        u32 rsvd0          : 2;
        u32 bei            : 1;
        u32 trb_type        : 6;
        u32 dir            : 1;
        u32 rsvd1          : 15;
    };
} xhci_normal_trb_t;
static_assert(sizeof(xhci_normal_trb_t) == sizeof(u32) * 4);


inline const char* trb_completion_code_to_string(const u8 completion_code) {
    switch (completion_code) {
    case XHCI_TRB_COMPLETION_CODE_INVALID:
        return "INVALID";
    case XHCI_TRB_COMPLETION_CODE_SUCCESS:
        return "SUCCESS";
    case XHCI_TRB_COMPLETION_CODE_DATA_BUFFER_ERROR:
        return "DATA_BUFFER_ERROR";
    case XHCI_TRB_COMPLETION_CODE_BABBLE_DETECTED_ERROR:
        return "BABBLE_DETECTED_ERROR";
    case XHCI_TRB_COMPLETION_CODE_USB_TRANSACTION_ERROR:
        return "USB_TRANSACTION_ERROR";
    case XHCI_TRB_COMPLETION_CODE_TRB_ERROR:
        return "TRB_ERROR";
    case XHCI_TRB_COMPLETION_CODE_STALL_ERROR:
        return "STALL_ERROR";
    case XHCI_TRB_COMPLETION_CODE_RESOURCE_ERROR:
        return "RESOURCE_ERROR";
    case XHCI_TRB_COMPLETION_CODE_BANDWIDTH_ERROR:
        return "BANDWIDTH_ERROR";
    case XHCI_TRB_COMPLETION_CODE_NO_SLOTS_AVAILABLE:
        return "NO_SLOTS_AVAILABLE";
    case XHCI_TRB_COMPLETION_CODE_INVALID_STREAM_TYPE:
        return "INVALID_STREAM_TYPE";
    case XHCI_TRB_COMPLETION_CODE_SLOT_NOT_ENABLED:
        return "SLOT_NOT_ENABLED";
    case XHCI_TRB_COMPLETION_CODE_ENDPOINT_NOT_ENABLED:
        return "ENDPOINT_NOT_ENABLED";
    case XHCI_TRB_COMPLETION_CODE_SHORT_PACKET:
        return "SHORT_PACKET";
    case XHCI_TRB_COMPLETION_CODE_RING_UNDERRUN:
        return "RING_UNDERRUN";
    case XHCI_TRB_COMPLETION_CODE_RING_OVERRUN:
        return "RING_OVERRUN";
    case XHCI_TRB_COMPLETION_CODE_VF_EVENT_RING_FULL:
        return "VF_EVENT_RING_FULL";
    case XHCI_TRB_COMPLETION_CODE_PARAMETER_ERROR:
        return "PARAMETER_ERROR";
    case XHCI_TRB_COMPLETION_CODE_BANDWIDTH_OVERRUN:
        return "BANDWIDTH_OVERRUN";
    case XHCI_TRB_COMPLETION_CODE_CONTEXT_STATE_ERROR:
        return "CONTEXT_STATE_ERROR";
    case XHCI_TRB_COMPLETION_CODE_NO_PING_RESPONSE:
        return "NO_PING_RESPONSE";
    case XHCI_TRB_COMPLETION_CODE_EVENT_RING_FULL:
        return "EVENT_RING_FULL";
    case XHCI_TRB_COMPLETION_CODE_INCOMPATIBLE_DEVICE:
        return "INCOMPATIBLE_DEVICE";
    case XHCI_TRB_COMPLETION_CODE_MISSED_SERVICE:
        return "MISSED_SERVICE";
    case XHCI_TRB_COMPLETION_CODE_COMMAND_RING_STOPPED:
        return "COMMAND_RING_STOPPED";
    case XHCI_TRB_COMPLETION_CODE_COMMAND_ABORTED:
        return "COMMAND_ABORTED";
    case XHCI_TRB_COMPLETION_CODE_STOPPED:
        return "STOPPED";
    case XHCI_TRB_COMPLETION_CODE_STOPPED_LENGTH_INVALID:
        return "STOPPED_LENGTH_INVALID";
    case XHCI_TRB_COMPLETION_CODE_STOPPED_SHORT_PACKET:
        return "STOPPED_SHORT_PACKET";
    case XHCI_TRB_COMPLETION_CODE_MAX_EXIT_LATENCY_ERROR:
        return "MAX_EXIT_LATENCY_ERROR";
    default:
        return "UNKNOWN_COMPLETION_CODE";
    }
}

inline const char* trb_type_to_string(const u8 trb_type) {
    switch (trb_type) {
    case XHCI_TRB_TYPE_RESERVED: return "XHCI_TRB_TYPE_RESERVED";
    case XHCI_TRB_TYPE_NORMAL: return "XHCI_TRB_TYPE_NORMAL";
    case XHCI_TRB_TYPE_SETUP_STAGE: return "XHCI_TRB_TYPE_SETUP_STAGE";
    case XHCI_TRB_TYPE_DATA_STAGE: return "XHCI_TRB_TYPE_DATA_STAGE";
    case XHCI_TRB_TYPE_STATUS_STAGE: return "XHCI_TRB_TYPE_STATUS_STAGE";
    case XHCI_TRB_TYPE_ISOCH: return "XHCI_TRB_TYPE_ISOCH";
    case XHCI_TRB_TYPE_LINK: return "XHCI_TRB_TYPE_LINK";
    case XHCI_TRB_TYPE_EVENT_DATA: return "XHCI_TRB_TYPE_EVENT_DATA";
    case XHCI_TRB_TYPE_NOOP: return "XHCI_TRB_TYPE_NOOP";
    case XHCI_TRB_TYPE_ENABLE_SLOT_CMD: return "XHCI_TRB_TYPE_ENABLE_SLOT_CMD";
    case XHCI_TRB_TYPE_DISABLE_SLOT_CMD: return "XHCI_TRB_TYPE_DISABLE_SLOT_CMD";
    case XHCI_TRB_TYPE_ADDRESS_DEVICE_CMD: return "XHCI_TRB_TYPE_ADDRESS_DEVICE_CMD";
    case XHCI_TRB_TYPE_CONFIGURE_ENDPOINT_CMD: return "XHCI_TRB_TYPE_CONFIGURE_ENDPOINT_CMD";
    case XHCI_TRB_TYPE_EVALUATE_CONTEXT_CMD: return "XHCI_TRB_TYPE_EVALUATE_CONTEXT_CMD";
    case XHCI_TRB_TYPE_RESET_ENDPOINT_CMD: return "XHCI_TRB_TYPE_RESET_ENDPOINT_CMD";
    case XHCI_TRB_TYPE_STOP_ENDPOINT_CMD: return "XHCI_TRB_TYPE_STOP_ENDPOINT_CMD";
    case XHCI_TRB_TYPE_SET_TR_DEQUEUE_PTR_CMD: return "XHCI_TRB_TYPE_SET_TR_DEQUEUE_PTR_CMD";
    case XHCI_TRB_TYPE_RESET_DEVICE_CMD: return "XHCI_TRB_TYPE_RESET_DEVICE_CMD";
    case XHCI_TRB_TYPE_FORCE_EVENT_CMD: return "XHCI_TRB_TYPE_FORCE_EVENT_CMD";
    case XHCI_TRB_TYPE_NEGOTIATE_BANDWIDTH_CMD: return "XHCI_TRB_TYPE_NEGOTIATE_BANDWIDTH_CMD";
    case XHCI_TRB_TYPE_SET_LATENCY_TOLERANCE_VALUE_CMD: return "XHCI_TRB_TYPE_SET_LATENCY_TOLERANCE_VALUE_CMD";
    case XHCI_TRB_TYPE_GET_PORT_BANDWIDTH_CMD: return "XHCI_TRB_TYPE_GET_PORT_BANDWIDTH_CMD";
    case XHCI_TRB_TYPE_FORCE_HEADER_CMD: return "XHCI_TRB_TYPE_FORCE_HEADER_CMD";
    case XHCI_TRB_TYPE_NOOP_CMD: return "XHCI_TRB_TYPE_NOOP_CMD";
    case XHCI_TRB_TYPE_GET_EXTENDED_PROPERTY_CMD: return "XHCI_TRB_TYPE_GET_EXTENDED_PROPERTY_CMD";
    case XHCI_TRB_TYPE_SET_EXTENDED_PROPERTY_CMD: return "XHCI_TRB_TYPE_SET_EXTENDED_PROPERTY_CMD";
    case XHCI_TRB_TYPE_TRANSFER_EVENT: return "XHCI_TRB_TYPE_TRANSFER_EVENT";
    case XHCI_TRB_TYPE_CMD_COMPLETION_EVENT: return "XHCI_TRB_TYPE_CMD_COMPLETION_EVENT";
    case XHCI_TRB_TYPE_PORT_STATUS_CHANGE_EVENT: return "XHCI_TRB_TYPE_PORT_STATUS_CHANGE_EVENT";
    case XHCI_TRB_TYPE_BANDWIDTH_REQUEST_EVENT: return "XHCI_TRB_TYPE_BANDWIDTH_REQUEST_EVENT";
    case XHCI_TRB_TYPE_DOORBELL_EVENT: return "XHCI_TRB_TYPE_DOORBELL_EVENT";
    case XHCI_TRB_TYPE_HOST_CONTROLLER_EVENT: return "XHCI_TRB_TYPE_HOST_CONTROLLER_EVENT";
    case XHCI_TRB_TYPE_DEVICE_NOTIFICATION_EVENT: return "XHCI_TRB_TYPE_DEVICE_NOTIFICATION_EVENT";
    default: return "UNKNOWN_TRB_TYPE";
    }
}

#endif // XHCI_TRB_H
